src/Insta/PlanningBundle/Entity/Oral.php
<?php

namespace Insta\PlanningBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * Oral
 *
 * @ORM\Table()
 * @ORM\Entity
 */
class Oral extends Schedule
{

    /**
     *
     * @var ArrayCollection
     * @ORM\ManyToMany(targetEntity="Student", inversedBy="orals")
     **/
    protected $students;

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }
    /**
     * @var \DateTime
     */
    protected $datetime;

    /**
     * @var integer
     */
    protected $duration;

    /**
     * @var \Insta\PlanningBundle\Entity\Room
     */
    protected $room;

    /**
     * @var Course
     *
     * @ORM\ManyToOne(targetEntity="Course", inversedBy="orals")
     * @ORM\JoinColumn(name="course_id", referencedColumnName="id", onDelete="CASCADE")
     */
    protected $course;

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->students = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Set datetime
     *
     * @param \DateTime $datetime
     * @return Oral
     */
    public function setDatetime($datetime)
    {
        $this->datetime = $datetime;

        return $this;
    }

    /**
     * Get datetime
     *
     * @return \DateTime 
     */
    public function getDatetime()
    {
        return $this->datetime;
    }

    /**
     * Set duration
     *
     * @param integer $duration
     * @return Oral
     */
    public function setDuration($duration)
    {
        $this->duration = $duration;

        return $this;
    }

    /**
     * Get duration
     *
     * @return integer 
     */
    public function getDuration()
    {
        return $this->duration;
    }

    /**
     * Add students
     *
     * @param \Insta\PlanningBundle\Entity\Student $students
     * @return Oral
     */
    public function addStudent(\Insta\PlanningBundle\Entity\Student $students)
    {
        $this->students[] = $students;

        return $this;
    }

    /**
     * Remove students
     *
     * @param \Insta\PlanningBundle\Entity\Student $students
     */
    public function removeStudent(\Insta\PlanningBundle\Entity\Student $students)
    {
        $this->students->removeElement($students);
    }

    /**
     * Get students
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getStudents()
    {
        return $this->students;
    }

    /**
     * Set room
     *
     * @param \Insta\PlanningBundle\Entity\Room $room
     * @return Oral
     */
    public function setRoom(\Insta\PlanningBundle\Entity\Room $room = null)
    {
        $this->room = $room;

        return $this;
    }

    /**
     * Get room
     *
     * @return \Insta\PlanningBundle\Entity\Room 
     */
    public function getRoom()
    {
        return $this->room;
    }

    /**
     * Set course
     *
     * @param \Insta\PlanningBundle\Entity\Course $course
     * @return Oral
     */
    public function setCourse(\Insta\PlanningBundle\Entity\Course $course = null)
    {
        $this->course = $course;

        return $this;
    }

    /**
     * Get course
     *
     * @return \Insta\PlanningBundle\Entity\Course 
     */
    public function getCourse()
    {
        return $this->course;
    }
    /**
     * @var integer
     */
    protected $id;

    public function getStudentNames() {

        $names = array();

        foreach ($this->students as $student)
            $names[] = $student->getFullname();

        return $names;

    }


}

src/Insta/PlanningBundle/Entity/Schedule.php
<?php

namespace Insta\PlanningBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Schedule
 *
 * @ORM\Entity(repositoryClass="ScheduleRepository")
 * @ORM\Table(name="schedules")
 * @ORM\InheritanceType("SINGLE_TABLE")
 * @ORM\DiscriminatorColumn(name="discr", type="string")
 * @ORM\DiscriminatorMap({"lesson" = "Lesson", "oral" = "Oral"})
 */
class Schedule
{

    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="datetime", type="datetime")
     */
    protected $datetime;

    /**
     * @var integer
     *
     * @ORM\Column(name="duration", type="integer")
     */
    protected $duration;

    /**
     * @var Room
     *
     * @ORM\ManyToOne(targetEntity="Room")
     * @ORM\JoinColumn(name="room_id", referencedColumnName="id")
     */
    protected $room;

    /**
     * Set datetime
     *
     * @param \DateTime $datetime
     * @return Schedule
     */
    public function setDatetime($datetime)
    {
        $this->datetime = $datetime;

        return $this;
    }

    /**
     * Get datetime
     *
     * @return \DateTime 
     */
    public function getDatetime()
    {
        return $this->datetime;
    }

    /**
     * Set duration
     *
     * @param integer $duration
     * @return Schedule
     */
    public function setDuration($duration)
    {
        $this->duration = $duration;

        return $this;
    }

    /**
     * Get duration
     *
     * @return integer 
     */
    public function getDuration()
    {
        return $this->duration;
    }

    /**
     * Set room
     *
     * @param Room $room
     * @return Schedule
     */
    public function setRoom(Room $room = null)
    {
        $this->room = $room;

        return $this;
    }

    /**
     * Get room
     *
     * @return Room
     */
    public function getRoom()
    {
        return $this->room;
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return \DateTime
     */
    public function getEndDatetime() {

        $endDate = clone $this->datetime;
        $endDate->modify('+' . $this->duration . ' minutes');
        return $endDate;

    }

}

src/Insta/PlanningBundle/Entity/User.php
<?php

namespace Insta\PlanningBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use FOS\UserBundle\Entity\User as BaseUser;

use FOS\UserBundle\Model\GroupInterface;

/**
 * User
 *
 * @ORM\Entity
 * @ORM\Table(name="insta_user")
 * @ORM\InheritanceType("SINGLE_TABLE")
 * @ORM\DiscriminatorColumn(name="discr", type="string")
 * @ORM\DiscriminatorMap({"user" = "User", "teacher" = "Teacher", "student" = "Student", "tutor" = "Tutor"})
 */
class User extends BaseUser
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var string
     *
     * @ORM\Column(name="firstname", type="string", length=50, nullable=true)
     *
     */
    protected $firstname;

    /**
     * @var string
     *
     * @ORM\Column(name="lastname", type="string", length=100, nullable=true)
     *
     */
    protected $lastname;

    /**
     *
     * @var ArrayCollection
     *
     * @ORM\ManyToMany(targetEntity="Insta\PlanningBundle\Entity\Group", inversedBy="users")
     * @ORM\JoinTable(name="insta_user_user_group",
     *      joinColumns={@ORM\JoinColumn(name="user_id", referencedColumnName="id")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="group_id", referencedColumnName="id")}
     * )
     */
    protected $groups;


    public function __construct()
    {
        parent::__construct();
        $this->groups = new ArrayCollection();
        // your own logic
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Add groups
     *
     * @param \Insta\PlanningBundle\Entity\Group $groups
     * @return User
     */
    public function addGroup(GroupInterface $groups)
    {
        $this->groups[] = $groups;

        return $this;
    }

    /**
     * Remove groups
     *
     * @param GroupInterface|Group $groups
     *
     * @return $this|void
     */
    public function removeGroup(GroupInterface $groups)
    {
        $this->groups->removeElement($groups);
    }

    /**
     * Get groups
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getGroups()
    {
        return $this->groups;
    }

    /**
     * @return string
     */
    public function getClass() {
        return get_class($this);
    }

    /**
     * Set firstname
     *
     * @param string $firstname
     * @return User
     */
    public function setFirstname($firstname)
    {
        $this->firstname = $firstname;

        return $this;
    }

    /**
     * Get firstname
     *
     * @return string 
     */
    public function getFirstname()
    {
        return $this->firstname;
    }

    /**
     * Set lastname
     *
     * @param string $lastname
     * @return User
     */
    public function setLastname($lastname)
    {
        $this->lastname = $lastname;

        return $this;
    }

    /**
     * Get lastname
     *
     * @return string 
     */
    public function getLastname()
    {
        return $this->lastname;
    }

    public function getFullname() {
        return $this->firstname . " " . $this->lastname;
    }
}

src/Insta/PlanningBundle/Controller/PublicController.php
<?php

namespace Insta\PlanningBundle\Controller;

use Insta\PlanningBundle\Entity\Course;
use Insta\PlanningBundle\Entity\Schedule;
use Insta\PlanningBundle\Entity\Student;
use Insta\PlanningBundle\Entity\Teacher;
use Insta\PlanningBundle\Entity\Tutor;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;

/**
 * Class PublicController
 * @package Insta\PlanningBundle\Controller
 */
class PublicController extends Controller
{
    /**
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function indexAction()
    {
        return $this->render('PlanningBundle:Default:index.html.twig');
    }

    /**
     * @param $month
     * @param $year
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function planningAction($month, $year) {

        $doctrine = $this->getDoctrine();
        $user = $this->getUser();

        if ($this->isGranted('ROLE_ADMIN')) {
            $schedules = $doctrine->getRepository('PlanningBundle:Schedule')->findAll();

        } elseif ($user instanceof Student) {
            if (!is_null($user->getPromotion())) {
                $schedules = array_merge(
                    $user->getPromotion()->getLessons()->toArray() ,
                    $user->getOrals()->toArray()
                );
            } else {
                $schedules = $user->getOrals()->toArray();
            }

        } elseif ($user instanceof Teacher) {
            $schedules = array();
            foreach ($user->getCourses() as $course) {
                /** @var Course $course */
                $schedules = array_merge($schedules, $course->getLessons()->toArray(), $course->getOrals()->toArray() );
            }
        } elseif ($user instanceof Tutor) {
            $schedules = array();
            foreach ($user->getStudents() as $student) {
                /** @var Student $student */

                if (!is_null($student->getPromotion())) {
                    $schedules = array_merge($schedules, $student->getPromotion()->getLessons()->toArray(), $student->getOrals()->toArray() );
                } else {
                    $schedules = $student->getOrals()->toArray();
                }

            }
        } else {

            return $this->render('PlanningBundle:Public:no_planning.html.twig');

        }


        /** @var Schedule[][] $schedulesByDate */
        $schedulesByDate = array();
        foreach ($schedules as $schedule) {
            if (!isset($schedulesByDate[$schedule->getDatetime()->format('Y-m-j')]))
                $schedulesByDate[$schedule->getDatetime()->format('Y-m-j')] = array();

            $schedulesByDate[$schedule->getDatetime()->format('Y-m-j')][] = $schedule;
        }

        return $this->render('PlanningBundle:Public:base_planning.html.twig', array(
            'schedules'=>$schedulesByDate,
            'service' => $this->get('planning.holidays'),
            'time' => \DateTime::createFromFormat('m-Y', $month."-".$year)->format('U')

        ));

    }

    /**
     * @param Schedule $schedule
     *
     * @return \Symfony\Component\HttpFoundation\Response
     * @ParamConverter("schedule", options={"mapping":{"id" : "id"}})
     */
    public function showScheduleAction(Schedule $schedule) {

        return $this->render('PlanningBundle:Public:showSchedule.html.twig', array('schedule'=>$schedule));

    }
}

src/Insta/PlanningBundle/Resources/views/Public/base_planning.html.twig
{% extends 'PlanningBundle::layout.html.twig' %}

{% set column_width = 100 / 7 %}
{% block content %}

    {% set previousmonth = time %}
    {% set nextmonth = time %}
    {% set previousmonth = previousmonth|date_modify("-1 month") %}
    {% set nextmonth = nextmonth|date_modify("+1 month") %}

    <div>
        <div class="table-responsive">
        <table class="table table-bordered" id="planning">
            <thead>
            <tr>
                <th class="center">
                <span class="pull-left">
                    <a class="btn btn-default btn-xs" href="{{ path('planning_month', {
                    month : previousmonth|date('m'), year: previousmonth|date('Y')
                    }) }}"><span class="glyphicon glyphicon-chevron-left"></span> Mois précédent</a>
                </span>
                </th>
                <th colspan="5">{{ time|date('F')|trans }} {{ time|date('Y') }}</th>
                <th>
                <span class="pull-right">
                    <a class="btn btn-default btn-xs" href="{{ path('planning_month', {
                    month : nextmonth|date('m'), year: nextmonth|date('Y')
                    }) }}">Mois suivant <span class="glyphicon glyphicon-chevron-right"></span></a>
                </span>
                </th>
            </tr>
            <tr>
                <th>Dimanche</th>
                <th>Lundi</th>
                <th>Mardi</th>
                <th>Mercredi</th>
                <th>Jeudi</th>
                <th>Vendredi</th>
                <th>Samedi</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                {% set daysInMonth = time|date('t') %}
                {% set startDow = time|date('F 1\\s\\t Y')|date('w') %}
                {% set dow = startDow %}
                {% for day in range(1,daysInMonth) %}
                {% if loop.first and startDow != 0 %}
                    <td colspan="{{ startDow }}"></td>
                {% endif %}
                <td {% if service.holidayOn(day, time|date('m'), time|date('Y')) is not null %}class="bg-info" {% endif %}>
                    <div>
                        <div>
                            {{ day }}
                            {% if service.holidayOn(day, time|date('m'), time|date('Y')) is not null %}
                                - <i>{{ service.holidayOn(day, time|date('m'), time|date('Y')).name }}</i>
                            {% endif %}

                            <div class="btn-group btn-group-xs">
                                {% if schedules[ time|date('Y-m-') ~ day ] is defined %}
                                    {% set promoOn = [] %}
                                    {% for schedule in schedules[ time|date('Y-m-') ~ day ] %}


                                        {% if schedule.promotion is defined and schedule.promotion.id not in promoOn %}

                                            {# c'est un cours #}

                                            <a data-toggle="tooltip" data-placement="left" title="Promo {{ schedule.promotion.name }}" class="btn btn-default btn-xs schedule" href="#promo-{{ schedule.promotion.id }}-{{ schedule.datetime|date('d') }}">
                                                <span class="glyphicon glyphicon-resize-full"></span>
                                            </a>
                                            {% set promoOn = promoOn|merge([schedule.promotion.id]) %}
                                        {% elseif schedule.students is defined %}

                                            {# c'est un soutenance #}

                                            {% for student in schedule.students %}
                                                {% if student.promotion is not null and student.promotion.id not in promoOn %}
                                                    <a data-toggle="tooltip" data-placement="left" title="Promo {{ student.promotion.name }}" class="btn btn-default btn-xs schedule"  href="#promo-{{ student.promotion.id }}-{{ schedule.datetime|date('d') }}">
                                                        <span class="glyphicon glyphicon-resize-full"></span>
                                                    </a>

                                                    {% set promoOn = promoOn|merge([student.promotion.id]) %}

                                                {% endif %}
                                            {% endfor %}


                                        {% endif %}



                                    {% endfor %}
                                {% endif %}
                            </div>

                        </div>


                    </div>
                </td>
                {% if loop.last and dow != 6 %}
                    <td colspan="{{ 6 - dow }}">&nbsp;</td>
                {% endif %}
                {% if dow == 6 %}
                {% set dow = 0 %}
            </tr>
            <tr>
                {% else %}
                    {% set dow = dow + 1 %}
                {% endif %}
                {% endfor %}
            </tr>
            </tbody>
        </table>
        </div>
        {% for schedule_one_day in schedules %}
            {% set promoOn = [] %}
            {% for schedule in schedule_one_day %}
                {% if schedule.promotion is defined and schedule.promotion.id not in promoOn %}

                    {% include 'PlanningBundle:Public:div_promotion.html.twig' with { promotion : schedule.promotion, schedule : schedule } %}

                    {% set promoOn = promoOn|merge([schedule.promotion.id]) %}

                {% elseif schedule.students is defined %}

                    {# c'est un soutenance #}

                    {% for student in schedule.students %}
                        {% if student.promotion is not null and student.promotion.id not in promoOn %}

                            {% include 'PlanningBundle:Public:div_promotion.html.twig' with { promotion : student.promotion, schedule : schedule } %}

                            {% set promoOn = promoOn|merge([student.promotion.id]) %}

                        {% endif %}
                    {% endfor %}


                {% endif %}


                {% if schedule.promotion is defined %}
                    {% include 'PlanningBundle:Public:div_lesson.html.twig' with { schedule : schedule} %}
                {% elseif schedule.students %}
                    {% include 'PlanningBundle:Public:div_oral.html.twig' with { schedule : schedule} %}
                {% endif %}


        {% endfor %}
        {% endfor %}


    </div>



{% endblock %}

{% block stylesheets %}
    {{ parent() }}

    <style>

        div.progress-group > div.progress {
            margin: 0;
            border-radius: 0;
        }

        div.progress-group > div.progress:first-child {
            border-top-left-radius: 4px;
            border-top-right-radius: 4px;

        }

        div.progress-group > div.progress:not(:last-child) {
            box-shadow: none;
            border-bottom: 1px solid #e5e5e5;
        }

        div.progress-group > div.progress:not(:last-child) > div.progress-bar {
            box-shadow: none;
        }

        div.progress-group > div.progress:last-child {
            border-bottom-left-radius: 4px;
            border-bottom-right-radius: 4px;
        }


        div.progress-bar.progress-bar-transparent {
            background: #ffffff !important;
        }


        div.schedule-info {
            height: 0 !important;
            overflow: hidden;
            transition: all 500ms;
            -webkit-transition: all 500ms;
            -moz-transition: all 500ms;
            -o-transition: all 500ms;
        }
        div.schedule-info:target {
            height: 400px !important;
        }
        table#planning td, table#planning th {
            width: {{ column_width }}%;
            max-width: {{ column_width }}%;
            min-width: {{ column_width }}%;
        }

    </style>

{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script>
        $(function () {
            $('[data-toggle="tooltip"]').tooltip()
        })
    </script>
{% endblock %}

src/Insta/PlanningBundle/Resources/views/Public/div_lesson.html.twig
<div class="schedule-info" id="schedule-{{ schedule.id }}" >
    <div class="well well-sm">

        <a href="#" class="close"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></a>

        <h3>{{ schedule.course.name }} - {{ schedule.room.site.name }}, {{ schedule.room.name }}
            <small>{{ schedule.datetime|date('d/m/Y H\\hi') }} &rarr; {{ schedule.endDatetime|date('H\\hi') }}</small>
        </h3>
        <h4>Promo {{ schedule.promotion.name }} <small> - Intervenant : {{ schedule.course.teachers[0].fullname|default("") }}</small>
            <a class="pull-right btn btn-xs btn-info" href="#promo-{{ schedule.promotion.id }}-{{ schedule.datetime|date('d') }}">Voir le planning de la promotion </a>
        </h4>
        <div class="row">
            <dl class="dl-horizontal col-sm-6">
                <dt>Description</dt>
                <dd>{{ schedule.course.description }}</dd>
                <dd>{{ 'Plus d\'infos : '~ schedule.course.descriptionLink|default('Non défini')|raw }}</dd>
            </dl>

            <dl class="dl-horizontal col-sm-6">
                <dt>Liens supplémentaires</dt>
                {% for link in schedule.course.variousLinks|default(['<i>Aucun lien</i>']) %}
                <dd>{{ link|raw }}</dd>
                {% endfor %}
            </dl>
        </div>
    </div>
</div>

src/Insta/PlanningBundle/Resources/views/Public/div_oral.html.twig
<div class="schedule-info" id="schedule-{{ schedule.id }}" >
    <div class="well well-sm">

        <a href="#" class="close"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></a>

        <h3>Soutenance {{ schedule.course.name }} - {{ schedule.room.site.name }}, {{ schedule.room.name }}
            <small>{{ schedule.datetime|date('d/m/Y H\\hi') }} &rarr; {{ schedule.endDatetime|date('H\\hi') }}</small>
        </h3>

        <h4>
            {{ schedule.studentNames|join }}
            <a class="pull-right btn btn-xs btn-info" href="#promo-{{ schedule.students[0].promotion.id|default('') }}-{{ schedule.datetime|date('d') }}">Voir le planning de la promotion </a>
        </h4>

    </div>
</div>

src/Insta/PlanningBundle/Resources/views/Public/div_promotion.html.twig
<div class="schedule-info" id="promo-{{ promotion.id }}-{{ schedule.datetime|date('d') }}">
    <div class="well well-sm">

        <a href="#" class="close"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></a>

        <h3>
            {{ schedule.datetime|date('d/m/Y') }} : Promo {{ promotion.name }}
        </h3>

        {% set time_9 = schedule.datetime %}
        {% set time_9 = time_9|date_modify('08:30') %}
        {% set time_18 = schedule.datetime %}
        {% set time_18 = time_18|date_modify('18:30') %}


        {% set planning = promotion.scheduleFor(schedule.datetime) %}
        {% set planning_simple = [] %}
        {% for time, schedule_day in planning %}
            {% if loop.first %}
                {% set planning_simple = planning_simple|merge( [  { 'start':time_9.timestamp, 'end': time }  ] ) %}
            {% endif %}
            {% set planning_simple = planning_simple|merge([{ 'start':time, 'end':time+schedule_day.duration*60, 'schedule':schedule_day } ]) %}



            {% if loop.last %}
                {% set planning_simple = planning_simple|merge( [  { 'start':time+schedule_day.duration*60, 'end': time_18.timestamp }  ] ) %}
            {% else %}
                {% set planning_simple = planning_simple|merge( [  { 'start':time+schedule_day.duration*60, 'end': planning[ planning|keys[loop.index0 +1] ].datetime.timestamp }  ] ) %}
            {% endif %}
        {% endfor %}

        <div class="progress-group">

            <div class="progress">
                {% set nb_schedule = 0 %}
                {% for planning in planning_simple %}
                    {% if planning.schedule is defined %}
                        {% set nb_schedule = nb_schedule +1 %}
                    {% endif %}
                    {% if (planning.end - planning.start) > 0 %}
                        <div class="progress-bar progress-bar-transparent {% if planning.schedule is defined %} progress-time {% endif %}" role="progressbar"
                             style="width: {{ (planning.end - planning.start) * (100/ (time_18|date('U')-time_9|date('U')) ) }}%;"
                                >
                            {% if planning.schedule is defined %}
                                <span class="pull-left text-muted hidden-xs">
                                            &nbsp;{{ planning.schedule.datetime|date('H:i') }}
                                        </span>
                                <span style="color: #000000">
                                                    {% if (planning.schedule.duration // 60) > 0  %}
                                                        {{ (planning.schedule.duration // 60) }} h
                                                    {% endif %}
                                    {% if (planning.schedule.duration % 60) > 0  %}
                                        {{ (planning.schedule.duration % 60) }} minutes
                                    {% endif %}
                                                </span>

                                <span class="pull-right text-muted hidden-xs">
                                            {{ planning.schedule.datetime|date_modify('+'~planning.schedule.duration*60~" seconds")|date('H:i') }}&nbsp;
                                        </span>

                            {% endif %}
                        </div>
                    {% endif %}
                {% endfor %}
            </div>

            <div class="progress" style="height: 22px">
                {% set nb_schedule = 0 %}
                {% for planning in planning_simple %}
                    {% if planning.schedule is defined %}
                        {% set nb_schedule = nb_schedule +1 %}
                    {% endif %}
                    {% if (planning.end - planning.start) > 0 %}
                        <div class="progress-bar
                                {% if planning.schedule is not defined %} progress-bar-transparent
                                {% elseif nb_schedule % 2 == 0 %} progress-bar-info
                                {% endif %}
                                {% if planning.schedule is defined and planning.schedule.students is defined %} progress-bar-striped
                                {% endif %}" role="progressbar"
                             style="width: {{ (planning.end - planning.start) * (100/ (time_18|date('U')-time_9|date('U')) ) }}%;"
                                >
                            {% if planning.schedule is defined %}

                                {% if planning.schedule.students is defined  %}
                                    <a class="btn btn-xs btn-warning" href="#schedule-{{ planning.schedule.id }}">Oral</a>
                                {% elseif planning.schedule.promotion is defined  %}
                                    <a class="btn btn-xs btn-default" href="#schedule-{{ planning.schedule.id }}">{{ planning.schedule.course.name }}</a>
                                {% endif %}
                            {% endif %}
                        </div>
                    {% endif %}
                {% endfor %}
            </div>

        </div>



    </div>
</div>

src/Insta/PlanningBundle/Resources/views/Public/no_planning.html.twig
{% extends 'PlanningBundle::layout.html.twig' %}

{% block stylesheets %}

{% endblock %}

{% block content %}
    <h1>Aucun planning disponible pour vous.</h1>
{% endblock %}

src/Insta/PlanningBundle/Resources/views/Public/showSchedule.html.twig
{% extends 'PlanningBundle::layout.html.twig' %}

{% block content %}

    {% if schedule.promotion is defined %}


        <div class="schedule-info" id="schedule-{{ schedule.id }}" >
            <div class="well well-lg">

                <h2>{{ schedule.course.name }} - {{ schedule.room.site.name }}, {{ schedule.room.name }}
                    <small>{{ schedule.datetime|date('H\\hi') }} &rarr; {{ schedule.endDatetime|date('H\\hi') }}</small>
                </h2>
                <h4>{{ schedule.promotion.name }} <small> - Intervenant : {{ schedule.course.teachers[0].fullname|default("") }}</small></h4>
                <div class="row">
                    <dl class="dl-horizontal col-sm-6">
                        <dt>Description</dt>
                        <dd>{{ schedule.course.description }}</dd>
                        <dd>{{ 'Plus d\'infos : '~ schedule.course.descriptionLink|default('Non défini')|raw }}</dd>
                    </dl>

                    <dl class="dl-horizontal col-sm-6">
                        <dt>Liens supplémentaires</dt>
                        {% for link in schedule.course.variousLinks|default(['<i>Aucun lien</i>']) %}
                            <dd>{{ link|raw }}</dd>
                        {% endfor %}
                    </dl>
                </div>
            </div>
        </div>


    {% elseif schedule.students is defined %}


        <div class="schedule-info" id="schedule-{{ schedule.id }}" >
            <div class="well well-lg">

                <h2>Soutenance {{ schedule.course.name }} - {{ schedule.room.site.name }}, {{ schedule.room.name }}
                    <small>{{ schedule.datetime|date('H\\hi') }} &rarr; {{ schedule.endDatetime|date('H\\hi') }}</small>
                </h2>

                <h4>
                    Participants : {{ schedule.studentNames|join }}
                </h4>

                <div class="row">
                    <dl class="dl-horizontal col-sm-6">
                        <dt>Description</dt>
                        <dd>{{ schedule.course.description }}</dd>
                        <dd>{{ 'Plus d\'infos : '~ schedule.course.descriptionLink|default('Non défini')|raw }}</dd>
                    </dl>

                    <dl class="dl-horizontal col-sm-6">
                        <dt>Liens supplémentaires</dt>
                        {% for link in schedule.course.variousLinks|default(['<i>Aucun lien</i>']) %}
                            <dd>{{ link|raw }}</dd>
                        {% endfor %}
                    </dl>
                </div>
            </div>
        </div>


    {% endif %}

{% endblock %}