src/Insta/PlanningBundle/Entity/Course.php
<?php

namespace Insta\PlanningBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * Course
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass = "CourseRepository")
 */
class Course
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255)
     */
    protected $name;

    /**
     * @var string
     *
     * @ORM\Column(name="description", type="string", length=255, nullable=true)
     */
    protected $description;

    /**
     * @var string
     *
     * @ORM\Column(name="descriptionLink", type="string", length=255, nullable=true)
     */
    protected $descriptionLink;

    /**
     * @var array
     *
     * @ORM\Column(name="variousLinks", type="array")
     */
    protected $variousLinks;

    /**
     *
     * @var ArrayCollection
     * @ORM\ManyToMany(targetEntity="Teacher", mappedBy="courses")
     **/
    protected  $teachers;

    /**
     * @var ArrayCollection
     * @ORM\OneToMany(targetEntity="Lesson", mappedBy="course")
     */
    protected $lessons;

    /**
     * @var ArrayCollection
     * @ORM\OneToMany(targetEntity="Oral", mappedBy="course")
     */
    protected $orals;



    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     * @return Course
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string 
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set description
     *
     * @param string $description
     * @return Course
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string 
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set descriptionLink
     *
     * @param string $descriptionLink
     * @return Course
     */
    public function setDescriptionLink($descriptionLink)
    {
        $this->descriptionLink = $descriptionLink;

        return $this;
    }

    /**
     * Get descriptionLink
     *
     * @return string 
     */
    public function getDescriptionLink()
    {
        return $this->descriptionLink;
    }

    /**
     * Set variousLinks
     *
     * @param array $variousLinks
     * @return Course
     */
    public function setVariousLinks($variousLinks)
    {
        $this->variousLinks = $variousLinks;

        return $this;
    }

    /**
     * Get variousLinks
     *
     * @return array 
     */
    public function getVariousLinks()
    {
        return $this->variousLinks;
    }
    /**
     * Constructor
     */
    public function __construct()
    {
        $this->teachers = new ArrayCollection();
        $this->variousLinks = array();
    }

    /**
     * Add teachers
     *
     * @param Teacher $teachers
     * @return Course
     */
    public function addTeacher(Teacher $teachers)
    {
        $this->teachers[] = $teachers;

        return $this;
    }

    /**
     * Remove teachers
     * @param Teacher $teachers
     */
    public function removeTeacher(Teacher $teachers)
    {
        $this->teachers->removeElement($teachers);
    }

    /**
     * Get teachers
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getTeachers()
    {
        return $this->teachers;
    }

    public function  getTeacherNames()
    {
        $teachernames=array();
        foreach($this->teachers as $teacher)
        {
            $teachernames[]=$teacher->getFullname();
        }
        return $teachernames;
    }

    /**
     * Add lessons
     *
     * @param \Insta\PlanningBundle\Entity\Lesson $lessons
     * @return Course
     */
    public function addLesson(\Insta\PlanningBundle\Entity\Lesson $lessons)
    {
        $this->lessons[] = $lessons;

        return $this;
    }

    /**
     * Remove lessons
     *
     * @param \Insta\PlanningBundle\Entity\Lesson $lessons
     */
    public function removeLesson(\Insta\PlanningBundle\Entity\Lesson $lessons)
    {
        $this->lessons->removeElement($lessons);
    }

    /**
     * Get lessons
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getLessons()
    {
        return $this->lessons;
    }

    /**
     * Add orals
     *
     * @param \Insta\PlanningBundle\Entity\Oral $orals
     * @return Course
     */
    public function addOral(\Insta\PlanningBundle\Entity\Oral $orals)
    {
        $this->orals[] = $orals;

        return $this;
    }

    /**
     * Remove orals
     *
     * @param \Insta\PlanningBundle\Entity\Oral $orals
     */
    public function removeOral(\Insta\PlanningBundle\Entity\Oral $orals)
    {
        $this->orals->removeElement($orals);
    }

    /**
     * Get orals
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getOrals()
    {
        return $this->orals;
    }
}

src/Insta/PlanningBundle/Entity/Teacher.php
<?php

namespace Insta\PlanningBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use FOS\UserBundle\Model\GroupInterface;

/**
 * Teacher
 *
 * @ORM\Entity(repositoryClass = "TeacherRepository")
 */
class Teacher extends User
{
    /**
     * @ORM\ManyToMany(targetEntity="Course", inversedBy="teachers")
     * @ORM\JoinTable(name="teacher_course",
     *      joinColumns={@ORM\JoinColumn(name="teacher_id", referencedColumnName="id", onDelete="CASCADE")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="course_id", referencedColumnName="id", onDelete="CASCADE")}
     *
     *      )
     **/
    protected $courses;
    /**
     * @var integer
     */
    protected $id;

    /**
     * @var \Doctrine\Common\Collections\Collection
     */
    protected $groups;

    /**
     * Constructor
     */
    public function __construct()
    {
        parent::__construct();
        $this->courses = new ArrayCollection();
        $this->groups = new ArrayCollection();
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Add courses
     *
     * @param Course $courses
     * @return Teacher
     */
    public function addCourse(Course $courses)
    {
        $this->courses[] = $courses;

        return $this;
    }

    /**
     * Remove courses
     *
     * @param Course $courses
     */
    public function removeCourse(Course $courses)
    {
        $this->courses->removeElement($courses);
    }

    /**
     * Get courses
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getCourses()
    {
        return $this->courses;
    }

    /**
     * Add groups
     *
     * @param \Insta\PlanningBundle\Entity\Group $groups
     * @return Teacher
     */
    public function addGroup(GroupInterface $groups)
    {
        $this->groups[] = $groups;

        return $this;
    }

    /**
     * Remove groups
     *
     * @param GroupInterface|Group $groups
     * @return $this|void
     */
    public function removeGroup(GroupInterface $groups)
    {
        $this->groups->removeElement($groups);
    }

    /**
     * Get groups
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getGroups()
    {
        return $this->groups;
    }
    /**
     * @var string
     */
    protected $firstname;

    /**
     * @var string
     */
    protected $lastname;


    /**
     * Set firstname
     *
     * @param string $firstname
     * @return Teacher
     */
    public function setFirstname($firstname)
    {
        $this->firstname = $firstname;

        return $this;
    }

    /**
     * Get firstname
     *
     * @return string 
     */
    public function getFirstname()
    {
        return $this->firstname;
    }

    /**
     * Set lastname
     *
     * @param string $lastname
     * @return Teacher
     */
    public function setLastname($lastname)
    {
        $this->lastname = $lastname;

        return $this;
    }

    /**
     * Get lastname
     *
     * @return string 
     */
    public function getLastname()
    {
        return $this->lastname;
    }

    public function removeCourses()
    {
        foreach ($this->courses->toArray() as $course) {
            $this->courses->removeElement($course);
        }

        return $this;
    }

    public function getRoles(){
        return array_merge(parent::getRoles(), array('ROLE_TEACHER'));
    }

    public function getCourseNames()
    {
        $names=array();
        $courses=$this->getCourses();
        foreach($courses as $course)
        {
            $names[]=$course->getName();
        }
        return $names;
    }

    public function isFreeFor(Schedule $inputSchedule) {

        /** @var Schedule[] $schedules */
        $schedules = array();
        foreach ($this->courses as $course) {
            /** @var Course $course */
            $schedules = array_merge($schedules, $course->getOrals()->toArray());
            $schedules = array_merge($schedules, $course->getLessons()->toArray());
        }

        foreach ($schedules as $schedule) {
            if ( $schedule->getEndDatetime() > $inputSchedule->getDatetime() &&
                $schedule->getDatetime() < $inputSchedule->getEndDatetime() ) {
                return false;
            }
        }

        return true;

    }
}

src/Insta/PlanningBundle/Entity/User.php
<?php

namespace Insta\PlanningBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use FOS\UserBundle\Entity\User as BaseUser;

use FOS\UserBundle\Model\GroupInterface;

/**
 * User
 *
 * @ORM\Entity
 * @ORM\Table(name="insta_user")
 * @ORM\InheritanceType("SINGLE_TABLE")
 * @ORM\DiscriminatorColumn(name="discr", type="string")
 * @ORM\DiscriminatorMap({"user" = "User", "teacher" = "Teacher", "student" = "Student", "tutor" = "Tutor"})
 */
class User extends BaseUser
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var string
     *
     * @ORM\Column(name="firstname", type="string", length=50, nullable=true)
     *
     */
    protected $firstname;

    /**
     * @var string
     *
     * @ORM\Column(name="lastname", type="string", length=100, nullable=true)
     *
     */
    protected $lastname;

    /**
     *
     * @var ArrayCollection
     *
     * @ORM\ManyToMany(targetEntity="Insta\PlanningBundle\Entity\Group", inversedBy="users")
     * @ORM\JoinTable(name="insta_user_user_group",
     *      joinColumns={@ORM\JoinColumn(name="user_id", referencedColumnName="id")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="group_id", referencedColumnName="id")}
     * )
     */
    protected $groups;


    public function __construct()
    {
        parent::__construct();
        $this->groups = new ArrayCollection();
        // your own logic
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Add groups
     *
     * @param \Insta\PlanningBundle\Entity\Group $groups
     * @return User
     */
    public function addGroup(GroupInterface $groups)
    {
        $this->groups[] = $groups;

        return $this;
    }

    /**
     * Remove groups
     *
     * @param GroupInterface|Group $groups
     *
     * @return $this|void
     */
    public function removeGroup(GroupInterface $groups)
    {
        $this->groups->removeElement($groups);
    }

    /**
     * Get groups
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getGroups()
    {
        return $this->groups;
    }

    /**
     * @return string
     */
    public function getClass() {
        return get_class($this);
    }

    /**
     * Set firstname
     *
     * @param string $firstname
     * @return User
     */
    public function setFirstname($firstname)
    {
        $this->firstname = $firstname;

        return $this;
    }

    /**
     * Get firstname
     *
     * @return string 
     */
    public function getFirstname()
    {
        return $this->firstname;
    }

    /**
     * Set lastname
     *
     * @param string $lastname
     * @return User
     */
    public function setLastname($lastname)
    {
        $this->lastname = $lastname;

        return $this;
    }

    /**
     * Get lastname
     *
     * @return string 
     */
    public function getLastname()
    {
        return $this->lastname;
    }

    public function getFullname() {
        return $this->firstname . " " . $this->lastname;
    }
}

src/Insta/PlanningBundle/Resources/views/Teacher/_layout_teacher.html.twig
{% extends 'PlanningBundle::layout.html.twig' %}

{% set route = app.request.attributes.get('_route') %}

{% block content %}

    <div class="col-sm-9">
        {% block main %}{% endblock %}
    </div>

    <div class="col-sm-3">

        <ul class="nav nav-pills nav-stacked">
            <li {% if 'teacher' in route %}class="active"{% endif %}
                    ><a href="{{ path('teacher_list') }}">Gestion des professeurs</a></li>
            <li {% if 'course' in route %}class="active"{% endif %}
                    ><a href="{{ path('course_list') }}">Gestion des cours</a></li>
        </ul>

    </div>



{% endblock %}

src/Insta/PlanningBundle/Resources/views/Teacher/addCourse.html.twig
{% extends "PlanningBundle:Teacher:_layout_teacher.html.twig" %}
{% block title %}Ajout d'un cour{% endblock %}
{% form_theme form 'bootstrap_3_horizontal_layout.html.twig' %}
{% block main %}
    <h1>Ajout d'un cour</h1>
    {{ form(form) }}
{% endblock %}

src/Insta/PlanningBundle/Resources/views/Teacher/addTeacher.html.twig
{% extends "PlanningBundle:Teacher:_layout_teacher.html.twig" %}
{% block title %}Ajout d'un professeur{% endblock %}
{% form_theme form 'bootstrap_3_horizontal_layout.html.twig' %}
{% block main %}
    <h1>Ajout d'un professeur</h1>
    {{ form(form) }}
{% endblock %}

src/Insta/PlanningBundle/Resources/views/Teacher/course.html.twig
{% extends "PlanningBundle:Teacher:_layout_teacher.html.twig" %}

{% block title %}Affichage d'un cour{% endblock %}

{% block jumbotron %}
    <div class="jumbotron">
        <div class="container">
            <h1>{{ course.name }}</h1>
            <p>{{ course.description }}</p>
        </div>
    </div>
{% endblock %}

{% block main %}
    <dl class="dl-horizontal col-lg-5">
        <dt>Lien URL</dt>
        <dd><a href="{{ course.descriptionLink}}">{{ course.descriptionLink}}</a></dd>
        <dt>Professeur</dt>
        <dd>{{ course.teacherNames|join }}</dd>
        <dd><a class="btn btn-primary btn-xs" href="{{ path('edit_course', {id : course.id}) }}">Modifier</a></dd>
    </dl>
{% endblock %}

src/Insta/PlanningBundle/Resources/views/Teacher/courseList.html.twig
{% extends "PlanningBundle:Teacher:_layout_teacher.html.twig" %}

{% block title %}PlanningBundle:Location:courseList{% endblock %}

{% block main %}
    <h1>Liste des cours<small> <a class="btn btn-primary" href="{{ path("add_course")  }}">Ajouter un cours</a></small></h1>
    <table class="table table-striped">
        <thead>
        <tr>
            <th>#</th>
            <th>Nom du cours</th>
            <th>Professeur</th>
            <th>Action</th>
        </tr>
        </thead>
        {% for course in courses %}
            <tr>
                <td>{{ course.id }}</td>
                <td>{{ course.name }}</td>
                <td>{{ course.teacherNames|join }}</td>
                <td>
                    <div class="btn-group" role="group" aria-label="...">
                        <a class="btn btn-primary btn-xs" href="{{ path("course",{id:course.id})  }}">Afficher</a>
                        <a class="btn btn-info btn-xs" href="{{ path('edit_course', {id:course.id})  }}">Editer</a>
                    </div>
                </td>
            </tr>
        {% endfor %}
    </table>

{% endblock %}

src/Insta/PlanningBundle/Resources/views/Teacher/editCourse.html.twig
{% extends "PlanningBundle:Teacher:_layout_teacher.html.twig" %}

{% block title %}PlanningBundle:Location:addCourse{% endblock %}

{% form_theme form 'bootstrap_3_horizontal_layout.html.twig' %}

{% block content %}

    <h2>Modification du cours : {{ course.name }}<small class="pull-right"><a href="{{ path("delete_course",{id:course.id}) }}" class="btn btn-warning btn-xs">Supprimer</a></small></h2>

    {{ form(form) }}

{% endblock %}

src/Insta/PlanningBundle/Resources/views/Teacher/editTeacher.html.twig
{% extends "PlanningBundle:Teacher:_layout_teacher.html.twig" %}

{% block title %}PlanningBundle:Teacher:editTeacher{% endblock %}

{% form_theme form 'bootstrap_3_horizontal_layout.html.twig' %}

{% block content %}

    <h2>Modification du professeur : {{teacher.firstname~" "~teacher.lastname}}  <small class="pull-right"><a href="{{ path("delete_teacher",{name:teacher.usernameCanonical}) }}" class="btn btn-warning btn-xs">Supprimer</a></small></h2>

    {{ form(form) }}



{% endblock %}

src/Insta/PlanningBundle/Resources/views/Teacher/index.html.twig
{% extends 'PlanningBundle:Teacher:_layout_teacher.html.twig' %}

{% block jumbotron %}

    <div class="jumbotron">
        <div class="container">
            <h1>{{ teachers|length }} professeur(s) et {{ courses|length }} cour(s)</h1>
            <dl class="dl-horizontal">
                {% for teacher in teachers %}
                    <dt>{{ teacher.fullname }}</dt>
                    <dd>{{ teacher.courses|length }} cour(s)</dd>
                {% endfor %}
            </dl>
        </div>
    </div>

{% endblock %}


{% block main %}
    <div class="col-md-6">
        <fieldset>
            <legend>Professeur
                <div class="btn-group btn-group-xs pull-right">
                    <a href="{{ path('teacher_list') }}" class="btn btn-xs btn-primary">Liste complète</a>
                    <a href="{{ path('add_teacher') }}" class="btn btn-xs btn-info">Ajouter un professeur</a>
                </div>
            </legend>
            <div>
                <dl class="dl-horizontal">
                    <dt>Nombre de professeur/dt>
                    <dd>{{ teachers|length }}</dd>
                </dl>
            </div>
        </fieldset>
    </div>
    <div class="col-md-6">
        <fieldset>
            <legend>Cours <small class="pull-right"><a href="{{ path('add_course') }}" class="btn btn-xs btn-default">Ajouter un cours</a></small></legend>
            <dl class="dl-horizontal">
                {% for course in courses %}
                    <dt>{{ course.name }}</dt>
                    <dd>
                        <div class="btn-group" role="group" aria-label="...">
                            <a class="btn btn-default btn-xs" href="{{ path("course",{id : course.id}) }}">Afficher</a>
                            <a class="btn btn-info btn-xs" href="{{ path("edit_course",{id : course.id}) }}">Editer</a>
                        </div>
                    </dd>
                    <dd>{{ course.teachers|length }} cours</dd>
                {% endfor %}
            </dl>
        </fieldset>
    </div>
{% endblock %}

src/Insta/PlanningBundle/Resources/views/Teacher/listTeacher.html.twig
{% extends "PlanningBundle:Teacher:_layout_teacher.html.twig" %}

{% block title %} Liste des professeurs {% endblock %}

{% block main %}
    <h1>Liste des professeurs <small> <a class="btn btn-primary" href="{{ path("add_teacher")  }}">Ajouter un professeur</a></small></h1>
    <table class="table">
        <thead>
        <tr>
            <th>#</th>
            <th>Username</th>
            <th>Nom complet</th>
            <th>Email</th>
            <th>Cours</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        {% for teacher in teachers %}
            <tr>
                <th>{{ teacher.id }}</th>
                <th>{{ teacher.usernameCanonical }}</th>
                <td>{{ teacher.firstname~" "~teacher.lastname }}</td>
                <td>{{ teacher.email }}</td>
                <td>{{ teacher.courseNames|join(', ') }}</td>
                <td>
                    <div class="btn-group" role="group" aria-label="...">
                        <a class="btn btn-primary btn-xs" href="{{ path("teacher",{name:teacher.usernameCanonical})  }}">Afficher</a>
                        <a class="btn btn-info btn-xs" href="{{ path("edit_teacher",{name:teacher.username})  }}">Editer</a>
                    </div>
                </td>
            </tr>
        {% endfor %}
        </tbody>

    </table>

{% endblock %}

src/Insta/PlanningBundle/Resources/views/Teacher/teacher.html.twig
{% extends "PlanningBundle:Teacher:_layout_teacher.html.twig" %}

{% block title %}Affichage d'un professeur{% endblock %}
{% block jumbotron %}
    <div class="jumbotron">
        <div class="container">
            <h1>{{ teacher.firstname ~ " " ~ teacher.lastname|upper() }}</h1>
        </div>
    </div>
{% endblock %}
{% block main %}
    <dl class="dl-horizontal col-lg-5">
        <dt>Email</dt>
        <dd>{{ teacher.email}}</dd>
        <dt>Cours</dt>
        {% for course in teacher.courses %}
        <dd>{{ course.name }}</dd>
        {% endfor %}
        <dd><a class="btn btn-primary btn-xs" href="{{ path('edit_teacher', {name:teacher.usernameCanonical}) }}">Modifier</a></dd>
    </dl>
{% endblock %}